bug fixed
1killerbehindyou1/Spectral_Display_GUI pull request #14
Opened 2023-01-19 07:52 UTC by 1killerbehindyou1

The current value set with the slider is used to render the image.

2023-01-20 10:39 UTC, Nutek requested changes

2023-01-20 10:39 UTC, Nutek commented on BasicGUI/QMLSources/main.qml
> +       //visible: bool
Why commented?

2023-01-20 10:39 UTC, Nutek commented on BasicGUI/QMLSources/main.qml
> +        //fileMode: FileDialog.SaveFile | FileDialog.OpenFile
Comment?

2023-01-31 17:16 UTC, 1killerbehindyou1 commented on BasicGUI/QMLSources/main.qml
> +        //fileMode: FileDialog.SaveFile | FileDialog.OpenFile
removed

2023-01-31 17:16 UTC, 1killerbehindyou1 commented on BasicGUI/QMLSources/main.qml
> +       //visible: bool
removed

2023-02-03 14:06 UTC, Nutek approved these changes

2023-02-06 17:47 UTC, merged